name = "M_CLI"
version = "0.1.0"
license = "Public Domain"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John S. Urban"

[library]
source-dir="src"

[[test]]   name="demo_check_commandline"  source-dir="demos/check_commandline"  main="check_commandline.f90"
[[test]]   name="demo_commandline"        source-dir="demos/commandline"        main="commandline.f90"
[[test]]   name="demo_M_CLI"              source-dir="demos/M_CLI"              main="M_CLI.f90"
[[test]]   name="demo_print_dictionary"   source-dir="demos/print_dictionary"   main="print_dictionary.f90"

[[executable]]   name="demo1"  source-dir="PROGRAMS/demo1"  main="demo1.f90"
[[executable]]   name="demo2"  source-dir="PROGRAMS/demo2"  main="demo2.f90"
[[executable]]   name="demo3"  source-dir="PROGRAMS/demo3"  main="demo3.f90"
[[executable]]   name="demo4"  source-dir="PROGRAMS/demo4"  main="demo4.f90"
[[executable]]   name="demo5"  source-dir="PROGRAMS/demo5"  main="demo5.f90"
[[executable]]   name="demo6"  source-dir="PROGRAMS/demo6"  main="demo6.f90"
[[executable]]   name="demo7"  source-dir="PROGRAMS/demo7"  main="demo7.f90"
